CC := clang
CFLAGS :=  -O0 -std=c89 -Wall -Wextra -Werror -Wformat=2 -Wunused-variable -Wno-implicit-int -Wno-return-type -pedantic
BIN := exe/

.PHONY: all clean

all:
	$(CC) $(CFLAGS) exercise-1-1.c -o $(BIN)exercise-1-1.exe
	$(CC) $(CFLAGS) exercise-1-2.c -o $(BIN)exercise-1-2.exe
	$(CC) $(CFLAGS) exercise-1-3.c -o $(BIN)exercise-1-3.exe
	$(CC) $(CFLAGS) exercise-1-4.c -o $(BIN)exercise-1-4.exe
	$(CC) $(CFLAGS) exercise-1-5.c -o $(BIN)exercise-1-5.exe
	$(CC) $(CFLAGS) exercise-1-6.c -o $(BIN)exercise-1-6.exe
	$(CC) $(CFLAGS) exercise-1-7.c -o $(BIN)exercise-1-7.exe
	$(CC) $(CFLAGS) exercise-1-8.c -o $(BIN)exercise-1-8.exe
	$(CC) $(CFLAGS) exercise-1-9.c -o $(BIN)exercise-1-9.exe
	$(CC) $(CFLAGS) exercise-1-10.c -o $(BIN)exercise-1-10.exe
	$(CC) $(CFLAGS) exercise-1-11.c -o $(BIN)exercise-1-11.exe
	$(CC) $(CFLAGS) exercise-1-12.c -o $(BIN)exercise-1-12.exe
	$(CC) $(CFLAGS) exercise-1-13-horizontal.c -o $(BIN)exercise-1-13-horizontal.exe
	$(CC) $(CFLAGS) exercise-1-13-vertical.c -o $(BIN)exercise-1-13-vertical.exe
	$(CC) $(CFLAGS) exercise-1-14.c -o $(BIN)exercise-1-14.exe
	$(CC) $(CFLAGS) exercise-1-15.c -o $(BIN)exercise-1-15.exe
	$(CC) $(CFLAGS) exercise-1-16.c -o $(BIN)exercise-1-16.exe
	$(CC) $(CFLAGS) exercise-1-17.c -o $(BIN)exercise-1-17.exe
	$(CC) $(CFLAGS) exercise-1-18.c -o $(BIN)exercise-1-18.exe
	$(CC) $(CFLAGS) exercise-1-19.c -o $(BIN)exercise-1-19.exe
	$(CC) $(CFLAGS) exercise-1-20.c -o $(BIN)exercise-1-20.exe
	$(CC) $(CFLAGS) exercise-1-21.c -o $(BIN)exercise-1-21.exe
	$(CC) $(CFLAGS) exercise-1-22.c -o $(BIN)exercise-1-22.exe
	$(CC) $(CFLAGS) exercise-1-23.c -o $(BIN)exercise-1-23.exe
	$(CC) $(CFLAGS) exercise-1-24.c -o $(BIN)exercise-1-24.exe

clean:
	rm exe/*
